### ISSUE TITLE
Few-shot으로 Problem Generate하기

### ISSUE THREAD

**Issue by Ricepunchb** [JiHun-Lim/Prompter_Day_2023#2]
대부분의 문제는 few-shot 을 통해 풀이의 간단함, 정답의 존재여부는 차치하고 비슷한 문제를 많이 뽑아낼 수 있음을 확인.

![스크린샷, 2023-08-23 17-28-41](https://github.com/JiHun-Lim/Prompter_Day_2023/assets/133007331/0b1744da-f20a-48fe-93f6-6951a41c96ca)

Few-shot 사용예시:
1. Example로 원본 문제와 그것의 변형 문제를 1, 2개 정도 제시.
2. 많이 뽑아낸다.

**Comment by JiHun-Lim** [comment]
@Ricepunchb 
```
Simplify the expression sin(tan^-1(x)) 
```
혹시 이런것도 비슷한 질문이 여러 개 generate 되는지 한 번 확인해줄 수 있을까요??
위에서 사용한 model은 어떤 model인가요? gpt-3.5-turbo 인가요??

**Comment by Ricepunchb** [comment]
넵 `gpt-355-turbo` 입니다.
![스크린샷, 2023-08-23 17-44-53](https://github.com/JiHun-Lim/Prompter_Day_2023/assets/133007331/10cb2b3f-175b-4a52-b1bf-7a772d9395ac)
요청한 문제도 비슷한 문제를 잘 뽑아냅니다.

다만, `Prove that cos(sin^-1(x)) = sqrt(1-x^2)` 이런 유형은 문제가 일단 정답이어야 하는 경우라 잘 뽑아내질 못하고 있습니다.

**Comment by Ricepunchb** [comment]
Problem을 최대한 많이 generate 하고 검수하는 방법을 쓰는 중

**Comment by Ricepunchb** [comment]
Close as completed
