### ISSUE TITLE
증명 문제 Answer 작성시키기

### ISSUE THREAD

**Issue by Ricepunchb** [JiHun-Lim/Prompter_Day_2023#4]
![스크린샷, 2023-08-25 12-13-42](https://github.com/JiHun-Lim/Prompter_Day_2023/assets/133007331/5a172b1c-a1de-46bd-9b0e-a8317245f1b4)

GPT 3.5 turbo 사용
Chain of thoughts Prompting을 통해 Zero-shot으로도 이정도의 문제는 완벽한 답안을 주는것을 확인

**Comment by Ricepunchb** [comment]
![스크린샷, 2023-08-25 14-17-06](https://github.com/JiHun-Lim/Prompter_Day_2023/assets/133007331/219801bf-47b6-4a4a-82d1-ffc850942f96)

계산 실수 하는 경우 발견

**Comment by Ricepunchb** [comment]
![스크린샷, 2023-08-25 14-47-07](https://github.com/JiHun-Lim/Prompter_Day_2023/assets/133007331/1a053e94-41ef-47b1-9d4f-ab8047f90211)

같은 문제를 모델을 GPT-4로 바꾼 결과 결과를 굉장히 잘 뽑아냅니다

**Comment by Ricepunchb** [comment]
실험결과 gpt-3.5-turbo의 경우 하이퍼볼릭을 그냥 삼각함수로 다루는 등 자잘한 실수를 많이 보임.
반면 gpt-4의 경우 답안을 더 깔끔하고 적재적소에 필요한 정리를 이용하는 등 수학증명틱(?)하게 잘 써줌.

비용적인 측면을 고려하지 않으면, 간단한 답안 작성부터 증명문제는 당연히 gpt-4를 이용하는 것이 좋아보임.

**Comment by JiHun-Lim** [comment]
결과 공유할 때에 screenshot 말고 이런식으로 보여주면 좋을 것 같아요
```
text = "Make 5 problems similar with [If xy + e^y = e, find the value of y'' at the point where x = 0.]"
print(PG(text))
```
```
Sure! Here are five similar problems:

1. If (x^3 + 2x)y + e^(2y) = e, find the value of y'' at the point where x = 0.

2. If (x^2 - 3x + 1)y + e^(3y) = e, find the value of y'' at the point where x = 0.

3. If (2x^3 - x^2 + 3)y + e^(y^2) = e, find the value of y'' at the point where x = 0.

4. If (x^3 + 4x^2 - 2x + 1)y + e^(4y) = e, find the value of y'' at the point where x = 0.

5. If (3x^2 + 2x + 1)y + e^(2y^2) = e, find the value of y'' at the point where x = 0.
````

**Comment by JiHun-Lim** [comment]
Latex 쓰고 싶으면 이렇게 하면 됩니다.
 If $(3x^2 + 2x + 1)y + e^{2y^2} = e$, find the value of $y''$ at the point where $x = 0$.

**Comment by Ricepunchb** [comment]
Solution을 generate 할때마다 자꾸 다른 답과 답변이 나와서 비용, 시간적으로 너무 비효율적이었음.
아예 prompt에 어떤 방법과 생각 방향을 통해 답변을 적어 보라 했더니 그나마 효율적으로 나와서 Case by Case 로 이 방법을 쓰고 있음.

**Comment by Ricepunchb** [comment]
Closd as completed
